### ISSUE TITLE
Unable to access AD using PyAD

### ISSUE THREAD

**Issue by Vigzm1995** [zakird/pyad#128]
I'm trying to import Pyad and get the active user directory when i'm shown this error:

`Traceback (most recent call last):
  File ".\test.py", line 9, in <module>
    q.execute_query(
  File "C:\Users\VIMOHA\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyad\adquery.py", line 78, in execute_query
    self.__rs, self.__rc = command.Execute()
  File "<COMObject ADODB.Command>", line 2, in Execute
  File "C:\Users\VIMOHA\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\dynamic.py", line 287, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(*(dispid, LCID, wFlags, retType, argTypes) + args)
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'Active Directory', 'There is no such object on the server.\r\n', None, 0, -2147217865), None)`

Is there a workaround to solve this issue. Thanks.

**Comment by connorhess** [comment]
hello, 1 year and no responses, would also like to know as I have the same issue
