### ISSUE TITLE
problem with pyad installation 

### ISSUE THREAD

**Issue by tzuriely** [zakird/pyad#18]
when i try to setup i got error message:
C:\Users\tzurielya\Desktop\pyad-master>setup.py install
Traceback (most recent call last):
  File "C:\Users\tzurielya\Desktop\pyad-master\setup.py", line 26, in <module>
    long_description = read('README.rst'),
  File "C:\Users\tzurielya\Desktop\pyad-master\setup.py", line 7, in read
    return open(os.path.join(os.path.dirname(**file**), fname)).read()
  File "C:\Python33\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 6116: cha
racter maps to <undefined>

help please:)

**Comment by pieisround** [comment]
I recently had this same issue.

```
Traceback (most recent call last):
  File "C:\Users\pieisround\Downloads\pyad\setup.py", line 26, in <module>
    long_description = read('README.rst'),
  File "C:\Users\pieisround\Downloads\pyad\setup.py", line 7, in read
    return open(os.path.join(os.path.dirname(__file__), fname)).read()
  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 6332: cha
racter maps to <undefined>
```

If I change the trailing quotation mark in the Apache (the "License") and the "AS IS" in the next line the package will install.
