### ISSUE TITLE
Could not rename a computer name

### ISSUE THREAD

**Issue by eric-lich** [zakird/pyad#27]
Code:
computer = adcomputer.ADComputer.from_cn('WS-490')
# computer.rename('WS-4900')

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\utility\test.py", line 25, in <module>
    computer.rename('WS-4900')
  File "C:\Python27\lib\site-packages\pyad\adobject.py", line 419, in rename
    parent = self.parent_container
  File "C:\Python27\lib\site-packages\pyad\adobject.py", line 517, in __get_parent_container
    q.adjust_pyad_type()
  File "C:\Python27\lib\site-packages\pyad\adobject.py", line 512, in adjust_pyad_type
    raise Exception("Unkown type. Adjustment not possible.")
Exception: Unkown type. Adjustment not possible.

**Comment by Kipjr** [comment]
Is there a solution to this problem?
