### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by greeny88** [zakird/pyad#28]
I've created a script to pull information out of my default AD with no problem. I've now pointed to a different AD using this code.

```
pyad.set_defaults(ldap_server=u'bar.example.com', username=u'username', password=u'password')
```

But I am getting this error when the script is run.

> Traceback (most recent call last):
>  File "C:\path\to\file.py", line 168, in <module>
>    main()
>  File "C:\path\to\file.py", line 25, in main
>    q = adquery.ADQuery()
>  File "build\bdist.win32\egg\pyad\adquery.py", line 32, in **init**
>  File "C:\Python27\lib\site-packages\win32com\client\dynamic.py", line 576, in **setattr**
>    raise AttributeError("Property '%s.%s' can not be set." % (self._username_, attr))
> AttributeError: Property '<unknown>.value' can not be set.

I've tested using other tools and I do have access to that AD using the same server/login combo. Another thing I've tried is connecting to my default AD using credentials to see if I get the same error and I in fact do. 

Is this a bug in setting defaults or am I using that line incorrectly?

**Comment by zerok** [comment]
Hi :) Just wanted to :+1: @mallouris 's solution as this also seems to be fixing the problem for me.

**Comment by zakird** [comment]
Thanks for the solution @mallouris. I apparently lost track of this issue. I've made these changes in master: 1a4d266.

**Comment by JackLeEmmerdeur** [comment]
Hey all. The fix conceived by greeny88, implemented by mallouris and commited by zakird, works for me (Windows Server 2008 R2, just as with greeny88). I am a noob at packaging for pypi. Therefore I don't feel sufficiently competent to estimate the effort to package a new egg (or wheel) with the modified adquery.py, but I think it would do your project a favour to accomplish that. I started a project not long ago, where I made the mentioned changes on my dev-machine. The day I deployed it on the server, I couldn't connect. As I searched hours again for this issue (Doh! I mention it now in a readme for future project maintainers), I could believe others struggle as well with this, and don't checkout via git or read issues here.
