### ISSUE TITLE
Unable to query the AD after setting set_defaults with valid credentials

### ISSUE THREAD

**Issue by rakeshbabuseva** [zakird/pyad#59]
Hi,

I have tried without setting set_defaults its working fine and able get the data but if I set the default credentials to valid one then it throws "server is not operational error".

> >>> a =ADQuery()
> >>> a.execute_query(where_clause="name='ou1'")
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "pyad\adquery.py", line 78, in execute_query
>     self.__rs, self.__rc = command.Execute()
>   File "<COMObject ADODB.Command>", line 3, in Execute
>   File "C:\Python27\lib\site-packages\win32com\client\dynamic.py", line 282, in
> _ApplyTypes_
>     result = self._oleobj_.InvokeTypes(*(dispid, LCID, wFlags, retType, argTypes
> ) + args)
> pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, u'Active Director
> y', u'The server is not operational.\r\n', None, 0, -2147217865), None)
>

**Comment by rakeshbabuseva** [comment]
Issue got fixed.

 It is because of ssl problem.
