### ISSUE TITLE
PIP Install fails due to outdated version on PyPI

### ISSUE THREAD

**Issue by chrisgray79** [zakird/pyad#60]
PIP installation fails with 'pip install pyad' with the following result:

Collecting pyad
  Downloading pyad-0.5.14.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\cgray\AppData\Local\Temp\1\pip-build-d7g42e5w\pyad\setup.py", line 26, in <module>
        long_description = read('README.rst'),
      File "C:\Users\cgray\AppData\Local\Temp\1\pip-build-d7g42e5w\pyad\setup.py", line 7, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
      File "c:\users\cgray\python\venv\adobe\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 6116: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\cgray\AppData\Local\Temp\1\pip-build-d7g42e5w\pyad\

This is resulting from the quotes in the last paragraph of the readme. This has been corrected in the source files in the repository, but the package on PyPI is outdated.  

Will the package be updated on PyPI?

**Comment by zakird** [comment]
I just uploaded master to 0.5.16.

**Comment by spyoungtech** [comment]
Hmm. Not able to install via pip, but slightly different problem. Says that can't satisfy PyWin32 requirement even after installing `pypiwin32`

```
C:\WINDOWS\system32>pip install pypiwin32
Collecting pypiwin32
  Downloading pypiwin32-220-cp36-none-win_amd64.whl (9.0MB)
    100% |████████████████████████████████| 9.0MB 138kB/s
Installing collected packages: pypiwin32
Successfully installed pypiwin32-220

C:\WINDOWS\system32>pip3 install pyad
Collecting pyad
  Using cached pyad-0.5.16.tar.gz
Requirement already satisfied: setuptools in c:\program files\python36\lib\site-packages (from pyad)
Collecting pywin32 (from pyad)
  Could not find a version that satisfies the requirement pywin32 (from pyad) (from versions: )
No matching distribution found for pywin32 (from pyad)
```

Cloning the repo and installing from that does work, however. Should I open a separate issue for this @zakird ?

**Comment by JamesWaldock** [comment]
The version pip currently retrieves (0.5.16) seems to still include the dependency on pywin32. If you've got pypiwin32 installed then I assume `pip install --no-dependencies pyad` should get you going.

**Comment by woodlandhunter** [comment]
@zakird can you push a new release to pypi so pip can install using pypiwin32 ? Are there any other maintainers with access?
